/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const Link: typeof import("react-router-dom")["Link"];
  const NavLink: typeof import("react-router-dom")["NavLink"];
  const Navigate: typeof import("react-router-dom")["Navigate"];
  const Outlet: typeof import("react-router-dom")["Outlet"];
  const Route: typeof import("react-router-dom")["Route"];
  const Routes: typeof import("react-router-dom")["Routes"];
  const axios: typeof import("axios")["default"];
  const createRef: typeof import("react")["createRef"];
  const forwardRef: typeof import("react")["forwardRef"];
  const lazy: typeof import("react")["lazy"];
  const memo: typeof import("react")["memo"];
  const request: typeof import("./src/plugins/request")["default"];
  const router: typeof import("./src/plugins/router")["router"];
  const startTransition: typeof import("react")["startTransition"];
  const useCallback: typeof import("react")["useCallback"];
  const useContext: typeof import("react")["useContext"];
  const useDebugValue: typeof import("react")["useDebugValue"];
  const useDeferredValue: typeof import("react")["useDeferredValue"];
  const useEffect: typeof import("react")["useEffect"];
  const useGlobalStore: typeof import("./src/modules/global/store")["useGlobalStore"];
  const useHelloworldStore: typeof import("./src/modules/helloworld/store")["useHelloworldStore"];
  const useHref: typeof import("react-router-dom")["useHref"];
  const useId: typeof import("react")["useId"];
  const useImperativeHandle: typeof import("react")["useImperativeHandle"];
  const useInRouterContext: typeof import("react-router-dom")["useInRouterContext"];
  const useInsertionEffect: typeof import("react")["useInsertionEffect"];
  const useLayoutEffect: typeof import("react")["useLayoutEffect"];
  const useLinkClickHandler: typeof import("react-router-dom")["useLinkClickHandler"];
  const useLocation: typeof import("react-router-dom")["useLocation"];
  const useLoginStore: typeof import("./src/modules/login/store")["useLoginStore"];
  const useLostStore: typeof import("./src/modules/lost/store")["useLostStore"];
  const useMemo: typeof import("react")["useMemo"];
  const useNavigate: typeof import("react-router-dom")["useNavigate"];
  const useNavigationType: typeof import("react-router-dom")["useNavigationType"];
  const useOutlet: typeof import("react-router-dom")["useOutlet"];
  const useOutletContext: typeof import("react-router-dom")["useOutletContext"];
  const useParams: typeof import("react-router-dom")["useParams"];
  const useReducer: typeof import("react")["useReducer"];
  const useRef: typeof import("react")["useRef"];
  const useResolvedPath: typeof import("react-router-dom")["useResolvedPath"];
  const useRoutes: typeof import("react-router-dom")["useRoutes"];
  const useSearchParams: typeof import("react-router-dom")["useSearchParams"];
  const useSettingStore: typeof import("./src/modules/setting/store")["useSettingStore"];
  const useState: typeof import("react")["useState"];
  const useSyncExternalStore: typeof import("react")["useSyncExternalStore"];
  const useTopic: typeof import("./src/plugins/topic")["useTopic"];
  const useTransition: typeof import("react")["useTransition"];
}
